import type { Express } from "express";
import { connectPageBody } from "./connect-page.js";

export const logo = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" rx="56" fill="#101816"/><path d="M128 68a60 60 0 0 1 52 30" fill="none" stroke="#3dbe8b" stroke-width="16" stroke-linecap="round"/><path d="M176 68v36h-36" fill="none" stroke="#3dbe8b" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/><path d="M128 188a60 60 0 0 1-52-30" fill="none" stroke="#e7c27a" stroke-width="16" stroke-linecap="round"/><path d="M80 188v-36h36" fill="none" stroke="#e7c27a" stroke-width="16" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

const page = (title: string, body: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Renew</title><link rel="icon" href="/icon.svg"><style>body{margin:0;background:#101816;color:#f2f7f4;font:17px/1.65 system-ui}main{max-width:840px;margin:40px auto;padding:24px}a{color:#3dbe8b}h1{line-height:1.15;font-size:40px}h2{margin-top:32px}h3{margin:18px 0 6px}nav,footer{display:flex;flex-wrap:wrap;gap:18px}section{border:1px solid #2a4038;border-radius:16px;padding:22px;margin:22px 0}input,textarea,select,button{font:inherit;box-sizing:border-box;max-width:100%;padding:10px;border:1px solid #3d5c4e;border-radius:8px;background:#17211e;color:inherit}input,textarea{width:100%}label{display:block;margin:12px 0}button{cursor:pointer;margin:12px 8px 12px 0}code,pre{overflow-wrap:anywhere}pre{overflow:auto;background:#17211e;padding:12px;border-radius:8px}#message{white-space:pre-wrap}small{color:#b7c9c0}</style></head><body><main><nav><a href="/app">Renew workspace</a><a href="/connect">Connect an assistant</a><a href="/support">Support</a></nav><h1>${title}</h1>${body}<footer><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/data">Your data</a></footer></main></body></html>`;

export function installPublicPages(app: Express, baseUrl: string) {
  app.get("/access", (_req, res) => res.type("html").send(page("Renew access", `<p>Renewal tools are available to existing Renew accounts with an active Pro subscription or trial. This connection has no renewal-tool entitlement at present. It cannot change your plan or start a purchase.</p><p>Verify that you connected the intended account. <a href="/connections">Manage the connection</a> or <a href="/support">contact support</a> if access looks incorrect.</p>`)));
  app.get("/icon.svg", (_req, res) => res.type("svg").send(logo));
  app.get("/connect", (_req, res) => res.type("html").send(page("Connect an assistant", connectPageBody(baseUrl))));
  app.get("/privacy", (_req, res) => res.type("html").send(page("Privacy policy", `<p>Effective October 4, 2026. Renew is operated under the Hutchins App Studio brand. Contact the operator through our <a href="/support">private support form</a>.</p><h2>Information we process</h2><p>We process account identifiers and email provided at sign-in, subscription status and billing references, and renewal content intentionally sent through the workspace or connected tools: customer accounts, current entitlements, renewal offers, concession rules, and revisions. Support requests contain the reply email and message you provide.</p><p>We do not receive every conversation automatically. Tools receive only their submitted arguments. Do not include passwords, payment card details, or unrelated personal information in renewal terms.</p><h2>Why and where</h2><p>We use this information to provide renewal-term features, authenticate users, enforce subscriptions, respond to support, prevent abuse, and meet legal obligations. Supabase provides authentication and database hosting; the host you deploy provides the service; Google provides optional sign-in; Stripe processes payments. We do not store complete card numbers. Connected MCP clients, including ChatGPT, Claude, Gemini, Grok, Cursor, and other hosts you authorize, receive the renewal information their authorized tools request and apply their own privacy terms. Service providers may process information outside your country.</p><h2>Control and retention</h2><p>We do not sell renewal terms or use them to train our own models. Saved accounts remain until you delete them or request account deletion. Revision history remains with its account. <a href="/data">Export or delete accounts</a>, including after a subscription expires. Account deletion removes live terms, revisions, and offers; provider backups may persist according to provider retention and are not an instant erasure guarantee. Billing records may be retained for required accounting or dispute handling.</p><p>Use support to request account deletion, correction, access, or questions about retention. Support records are kept while resolving the request and as needed for security or legal obligations. The service uses sign-in storage to maintain your session. No advertising trackers are included.</p><h2>Security and changes</h2><p>Account authentication and database ownership rules protect private customer accounts. No service can promise absolute security. We publish policy changes here with an updated effective date. If local privacy law gives you additional rights, you may exercise them through support.</p>`)));
  app.get("/terms", (_req, res) => res.type("html").send(page("Terms of service", `<p>Effective October 4, 2026. These terms govern Renew, offered under the Hutchins App Studio brand. Questions and requests go through <a href="/support">support</a>.</p><h2>Your renewal terms</h2><p>You retain your rights in content you submit. You grant the operator permission to host, process, retrieve, and transmit it only as needed to provide the service. Submit only content you have the right to use. Do not use the service unlawfully, attempt unauthorized access, or disrupt other users.</p><h2>Accounts and paid access</h2><p>Use your own account and protect your sign-in. Renewal tools require Renew Pro or an active trial. The trial lasts 14 days. Billing interval, trial end, and payment terms are shown by Stripe before purchase. Trials may convert to recurring paid subscriptions as disclosed at checkout. Manage cancellation through the billing portal in your account. Cancellation does not automatically delete your data. Contact support for billing mistakes or refund requests; applicable consumer rights continue to apply.</p><h2>Renew has limits</h2><p>The assistant chooses when to invoke tools, subject to your permissions. Renew cannot promise that an assistant will always retrieve approved terms before it answers, or that it will refuse every unapproved concession. Review important saved facts and keep exports. Locked facts stay locked until you revise them. If a concession, a discount, or an extra entitlement is not approved, the tools say so.</p><h2>Service operation</h2><p>We may change features or restrict access to address abuse, security issues, nonpayment, or legal obligations. We aim to provide reliable access but cannot guarantee uninterrupted operation or error-free assistant output. These terms do not remove rights or remedies that applicable law does not permit us to exclude. Material updates will be published with an updated date.</p><h2>Leaving</h2><p>You can disconnect applications, export or delete accounts, cancel billing, and request account deletion. These are separate controls, described on <a href="/data">Your data</a>.</p>`)));
  app.get("/support", (_req, res) => res.type("html").send(page("Contact Renew", `<p>Send a private support, billing, privacy, or account-deletion request. Include a reply email. Do not send passwords, tokens, payment card details, or your full renewal record.</p><form id="support"><label>Reply email<input name="email" type="email" required maxlength="254"></label><label>How can we help?<textarea name="message" required minlength="10" maxlength="4000" rows="7"></textarea></label><button>Send request</button></form><p id="message" role="status"></p><script>document.getElementById('support').onsubmit=async function(e){e.preventDefault();var b=this.querySelector('button');b.disabled=true;try{var r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:this.email.value,message:this.message.value})});var d=await r.json();if(!r.ok)throw Error(d.error||'Unable to send');document.getElementById('message').textContent='Request received. Reference: '+d.id;this.reset()}catch(e){document.getElementById('message').textContent=e.message}finally{b.disabled=false}};</script>`)));
}

export { page };
